version: "3.8"
services:
  db:
    image: postgres:13.16
    restart: always
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  backend:
    build: .
    ports:
      - 80:8080
    volumes:
      - .:/app
      - /app/tmp
      - data:/app/data/db
    stdin_open: true
    tty: true

volumes:
  data:
  pgdata:
