version: "3.8"
services:
  backend:
    build: .
    ports:
      - 80:8080
    volumes:
      - .:/app
      - /app/tmp
      - /app/data
      - data:/app/data/db
    stdin_open: true
    tty: true

volumes:
  data:
